import Link from "next/link";
import type { Metadata } from "next";
import { ThemeToggle } from "@/components/ThemeToggle";

export const metadata: Metadata = { title: "Terms" };

export default function TermsPage() {
  return (
    <div className="mx-auto w-full max-w-2xl px-4 py-6 sm:px-6 sm:py-10">
      <header className="mb-8 flex items-center justify-between">
        <Link href="/" className="text-xl font-bold tracking-tight text-text">
          ADH<span className="text-accent">V</span>
        </Link>
        <ThemeToggle />
      </header>

      <main className="flex flex-col gap-4">
        <h1 className="text-2xl font-semibold text-text sm:text-3xl">Terms</h1>
        <p className="text-sm text-muted">
          Plain English. Last updated July 2026.
        </p>

        <Section title="What ADHV is">
          <p>
            ADHV helps you break down and start tasks. It is a productivity tool
            —{" "}
            <strong className="text-text">
              not medical advice, therapy, diagnosis, or treatment
            </strong>
            . If you&apos;re struggling with your mental health, please talk to
            a professional or someone you trust. In the UK you can call
            Samaritans free any time on 116 123.
          </p>
        </Section>

        <Section title="Your account">
          <p>
            You sign in with a magic link to your email. Keep access to that
            inbox secure — anyone who can read it can sign in as you. You must
            be 16 or older to use ADHV.
          </p>
        </Section>

        <Section title="Fair use of the AI">
          <p>
            The AI features cost real money to run, so free plans have daily
            limits and we may rate-limit or pause accounts that abuse the
            service (for example, automated bulk requests). Don&apos;t use ADHV
            to generate harmful, illegal, or abusive content.
          </p>
        </Section>

        <Section title="Payments">
          <p>
            Pro is billed through Stripe. Plans renew automatically until you
            cancel, which you can do any time in one tap from your{" "}
            <Link href="/account" className="text-accent hover:underline">
              account
            </Link>
            . Cancelling stops future charges and keeps Pro until the end of the
            period you&apos;ve paid for. The 7-day trial can be cancelled before
            it ends at no charge.
          </p>
        </Section>

        <Section title="The AI isn't perfect">
          <p>
            Steps are generated by an AI model and may sometimes be off. Use
            your judgement — you&apos;re in charge of what you actually do.
          </p>
        </Section>

        <Section title="Ending things">
          <p>
            You can delete your account and all your data any time from your
            account page. We can suspend accounts that break these terms.
          </p>
        </Section>

        <p className="mt-6 text-xs text-muted/80">
          ADHV is a self-management tool, not therapy or medical advice.
        </p>
      </main>

      <footer className="mt-12 border-t border-border pt-6 text-center text-sm text-muted">
        <div className="flex flex-wrap justify-center gap-x-5 gap-y-2">
          <Link href="/" className="hover:text-text">
            Home
          </Link>
          <Link href="/privacy" className="hover:text-text">
            Privacy
          </Link>
          <Link href="/app" className="hover:text-text">
            App
          </Link>
        </div>
      </footer>
    </div>
  );
}

function Section({
  title,
  children,
}: {
  title: string;
  children: React.ReactNode;
}) {
  return (
    <section className="text-muted">
      <h2 className="mb-1.5 text-lg font-semibold text-text">{title}</h2>
      {children}
    </section>
  );
}
